[project]
name = "mcp-server-web-search"
version = "1.0"
description = "Web Search MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.4",
    "requests==2.32.3",
]

[tool.hatch.metadata]
allow-direct-references = true

[project.scripts]
mcp-server-web-search = "mcp_server_web_search.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
