# 部署方式
DEPLOY_MODE_LOCAL = "local"
DEPLOY_MODE_REMOTE = "remote"

# API_NAME
API_CREATE_APP_INSTANCE = "/CreateAppInstance"
API_CREATE_APP_SCENE_META = "/CreateAppSceneMeta"
API_DESCRIBE_APP_INSTANCES = "/DescribeAppInstances"
API_DESCRIBE_SESSION_ANSWER = "/DescribeSessionAnswer"
API_CREATE_DOWNLOAD_TASK = "/CreateDownloadTask"
API_DESCRIBE_DOWNLOAD_TASKS = "/DescribeDownloadTasks"
API_DESCRIBE_DOWNLOAD_URL = "/DescribeDownloadUrl"
API_CREATE_HOST_GROUP = "/CreateHostGroup"
API_DELETE_HOST_GROUP = "/DeleteHostGroup"
API_DESCRIBE_HOST_GROUP = "/DescribeHostGroup"
API_DESCRIBE_HOST_GROUPS = "/DescribeHostGroups"
API_DESCRIBE_HOSTS = "/DescribeHosts"
API_DESCRIBE_HOST_GROUP_RULES = "/DescribeHostGroupRules"
API_CREATE_RULE = "/CreateRule"
API_DELETE_RULE = "/DeleteRule"
API_DESCRIBE_RULE = "/DescribeRule"
API_DESCRIBE_RULES = "/DescribeRules"
API_APPLY_RULE_TO_HOST_GROUPS = "/ApplyRuleToHostGroups"
API_DELETE_RULE_FROM_HOST_GROUPS = "/DeleteRuleFromHostGroups"
API_CREATE_ALARM_NOTIFY_GROUP = "/CreateAlarmNotifyGroup"
API_DELETE_ALARM_NOTIFY_GROUP = "/DeleteAlarmNotifyGroup"
API_DESCRIBE_ALARM_NOTIFY_GROUPS = "/DescribeAlarmNotifyGroups"
API_CREATE_ALARM = "/CreateAlarm"
API_DELETE_ALARM = "/DeleteAlarm"
API_DESCRIBE_ALARMS = "/DescribeAlarms"
