VOLCENGINE_ACCESS_KEY_HEADER = 'x-tt-access-key'
VOLCENGINE_SECRET_KEY_HEADER = 'x-tt-secret-key'
VOLCENGINE_SESSION_TOKEN_HEADER = 'x-tt-session-token'
VOLCENGINE_HOST_HEADER = 'x-tt-host'
VOLCENGINE_REGION_HEADER = 'x-tt-region'
VOLCENGINE_TOOLS_SOURCE_HEADER = 'x-tt-tools-source'
VOLCENGINE_TOOLS_TYPE_HEADER = 'x-tt-tools-type'



VOLCENGINE_ACCESS_KEY_ENV = 'VOLCENGINE_ACCESS_KEY'
VOLCENGINE_SECRET_KEY_ENV = 'VOLCENGINE_SECRET_KEY'
VOLCENGINE_SESSION_TOKEN_ENV = 'VOLCENGINE_SESSION_TOKEN'
VOLCENGINE_HOST_ENV = 'VOLCENGINE_HOST'
VOLCENGINE_REGION_ENV = 'VOLCENGINE_REGION'
VOLCENGINE_TOOLS_SOURCE_ENV = 'MCP_TOOLS_SOURCE'
VOLCENGINE_TOOLS_TYPE_ENV = 'MCP_TOOL_TYPE'